name: Generate Snake Game

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: tribhuwan-kumar
          output_file: dist/github-snake.svg
          capture_type: svg
