name: Generate Snake Game

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: tribhuwan-kumar
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: tribhuwan-kumar
          outputs: |
            dist/github-snake.svg
            dist/github-snake.gif
